# Blacklisting example
branches:
  except:
    - gh-pages

language: python
python:
  - "2.7"
env:
  - DJANGO=1.5.5 DB=postgres

# command to install dependencies
#install:
#  - "pip install -r requirements.txt"

before_script:
  - psql -c 'create database test_harvest_api;' -U postgres
script:
  - python manage.py test
